---
- name: Check if Centos-Base repo file exists
  stat:
    path: /etc/yum.repos.d/CentOS-Base.repo
  register: stat_result

- name: Create Centos-Base repo file if it doesn't exist
  copy: 
    src: files/CentOS-Base.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
    owner: root
    group: root
    mode: '644'
  when: not stat_result.stat.exists

- name: Enable or disable CENTOS repos(CentOS only)
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: "{{item}}"
    option: enabled
    value: "{{enable_flag}}"
  with_items: "{{repo_list}}"
  when:
     - (ansible_distribution == "CentOS")
     - ansible_distribution_major_version == "7"

